/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/dashboard.courses.$courseId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$courseId': {
      id: '/dashboard/courses/$courseId'
      path: '/$courseId'
      fullPath: '/dashboard/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
  }
}

interface DashboardCoursesRouteChildren {
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
